name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  build:
    name: Push Docker image to Docker Hubs
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: austinliannn/nus-iss-dmss

      - name: Build docker image
        run: docker build -t austinliannn/nus-iss-dmss .

      - name: Publish image to Docker Hub
        run: |
          docker tag austinliannn/nus-iss-dmss:latest austinliannn/nus-iss-dmss:server
          docker push austinliannn/nus-iss-dmss:server
          
  Deploy_to_EC2:
    needs: build
    runs-on: [ aws-ec2 ]
    steps:
      - name: Pull Image from docker hub
        run: docker pull austinliannn/nus-iss-dmss:server

      - name: Delete old container
        run: docker rm -f server-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name server-container austinliannn/nus-iss-dmss:server